"""Fix relationships

Revision ID: 4f82b4293af5
Revises: f62f0fec9412
Create Date: 2025-04-14 09:49:13.215665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f82b4293af5'
down_revision: Union[str, None] = 'f62f0fec9412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_authors', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paper_authors', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'paper_authors', 'authors', ['author'], ['name'])
    op.alter_column('paper_categories', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paper_categories', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'paper_categories', 'categories', ['category'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paper_categories', type_='foreignkey')
    op.alter_column('paper_categories', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paper_categories', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'paper_authors', type_='foreignkey')
    op.alter_column('paper_authors', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paper_authors', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
