"""add_user_paper_views_table

Revision ID: 83c36b5b52a9
Revises: 8a7c5b9e2f01
Create Date: 2025-04-19 09:53:42.625879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c36b5b52a9'
down_revision: Union[str, None] = '8a7c5b9e2f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_paper_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_paper_views_id'), 'user_paper_views', ['id'], unique=False)
    op.create_index(op.f('ix_user_paper_views_paper_id'), 'user_paper_views', ['paper_id'], unique=False)
    op.create_index(op.f('ix_user_paper_views_user_id'), 'user_paper_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_paper_views_view_date'), 'user_paper_views', ['view_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_paper_views_view_date'), table_name='user_paper_views')
    op.drop_index(op.f('ix_user_paper_views_user_id'), table_name='user_paper_views')
    op.drop_index(op.f('ix_user_paper_views_paper_id'), table_name='user_paper_views')
    op.drop_index(op.f('ix_user_paper_views_id'), table_name='user_paper_views')
    op.drop_table('user_paper_views')
    # ### end Alembic commands ###
