"""Remove paper_embeddings table

Revision ID: 86c7f7e9b13d
Revises: 4f82b4293af5
Create Date: 2025-04-14 10:02:45.422993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c7f7e9b13d'
down_revision: Union[str, None] = '4f82b4293af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_embeddings',
    sa.Column('paper_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name='paper_embeddings_paper_id_fkey'),
    sa.PrimaryKeyConstraint('paper_id', name='paper_embeddings_pkey')
    )
    # ### end Alembic commands ###
