"""remove_paper_extracted_text_and_update_user_preferences

Revision ID: f0481b28dab6
Revises: c366719085e2
Create Date: 2025-05-07 03:46:30.733712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0481b28dab6'
down_revision: Union[str, None] = 'c366719085e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_extracted_texts')
    op.add_column('user_preferences', sa.Column('ip_prefix', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('last_visited_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_preferences_ip_prefix'), 'user_preferences', ['ip_prefix'], unique=False)
    op.drop_column('user_preferences', 'preferences')
    op.drop_column('user_preferences', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_preferences_ip_prefix'), table_name='user_preferences')
    op.drop_column('user_preferences', 'last_visited_at')
    op.drop_column('user_preferences', 'ip_prefix')
    op.create_table('paper_extracted_texts',
    sa.Column('paper_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name='paper_extracted_texts_paper_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', name='paper_extracted_texts_pkey')
    )
    # ### end Alembic commands ###
