"""recreate_baseline_from_existing_database

Revision ID: fe7de2efa829
Revises: 
Create Date: 2025-05-15 10:20:22.489273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7de2efa829'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_analysis',
    sa.Column('paper_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_findings', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contributions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('methodology', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('limitations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('future_work', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name='paper_analysis_paper_id_fkey'),
    sa.PrimaryKeyConstraint('paper_id', name='paper_analysis_pkey')
    )
    # ### end Alembic commands ###
